[PLAYER-4099] Fix UI for iPads (Analytics)
ooyala/ios-sample-apps pull request #308
Opened 2018-10-03 17:34 UTC by cacel

2018-10-03 21:08 UTC, orobles-ooyala commented on PlaybackLab/DownloadToOwnSampleApp/DownloadToOwnSampleApp/Info.plist
> -		<string>UIInterfaceOrientationLandscapeLeft</string>
I'm not sure if this is correct approach. Does this affect the video fullscreen in landscape mode? Can't this be moved only to the view that you need and not the whole app?

2018-10-04 08:26 UTC, maxkupetskii requested changes
I can see that according to the ticket it requires another issue to be solved
_Save analytics data when device is offline_
Why all of a sudden it's a fix for UI?

2018-10-04 17:19 UTC, DmitriiMaslov commented
Guys, I would also ask to provide clear description for PRs and if you see this is not done in other PRs please do the same.

2018-10-04 18:24 UTC, cacel commented
@maxkupetskii The issue was solved in the iOS-SDK (core).
QA reported that the sample app was working fine for iPhone but for iPad the textView was overlapping the app. In the ticket you can see the last comment for QA: "On iPADs, The analytics window is overlapped on player."

@DmitriiMaslov fyi

2018-10-04 18:26 UTC, cacel commented
@orobles-ooyala Now the app can be used landscape and portrait, I added the constants in the plist file for your previous comment.

2018-10-04 19:53 UTC, orobles-ooyala approved these changes

2018-10-04 20:40 UTC, brol1dev approved these changes
@DmitriiMaslov, @maxkupetskii  I don't want to merge this one until you do a final look. Check it out and if you feel ok you can merge it.

Thanks

2018-10-05 06:51 UTC, merged