[Player 5463] Add configuration option to disable pause on app backgrounding
ooyala/ios-sample-apps pull request #377
Opened 2019-04-15 11:40 UTC by oSulyma

**Ticket goal:** Add configuration option to disable pause on app backgrounding
**How PR achieves the goal:**  Please see major description inside PR https://git.corp.ooyala.com/projects/PBA/repos/ios-sdk/pull-requests/506/overview for PLAYER-5463 in iOS-SDK. To enable background playback property of instance OOOptions was must be assigned to OOBackgroundPlaybackModeAllowed
**Affected repo-s:** Sample-Apps + ios-SDK (must be synchronized, switch for appropriate branch)
**Unit tests:** Unit test not added, because there is no test target for BasicPlayback-SA.
**SampleApp for testing**: BasicPlayback-SA (or any native SA). Please note: to enable background playback go to BasicSimplePlayerViewController -> -viewDidLoad: and change `options.backgroundMode` from `OOBackgroundPlaybackModeDenied` (that must be kept in repository as default) to `OOBackgroundPlaybackModeAllowed`

2019-04-15 15:39 UTC, Artur-Sakhno commented on BasicPlaybackSampleApp/BasicPlaybackSampleApp/Players/BasicSimplePlayerViewController.m
>  #import <OoyalaSDK/OoyalaSDK.h>
We can use `@import OoyalaSDK;` here

2019-04-15 15:39 UTC, Artur-Sakhno commented on BasicPlaybackSampleApp/BasicPlaybackSampleApp/Players/BasicSimplePlayerViewController.m
> +#import <OoyalaSDK/OOEnums.h>
Same `@import OoyalaSDK.OOEnums;`

2019-04-16 18:52 UTC, maxkupetskii requested changes
I think we have to check how `ControlsLockSampleApp` works now because it contains some manual code for altering `OoyalaSDK` behavior. So it's possible that this manual code should be either removed or changed

2019-04-17 09:47 UTC, oSulyma commented on BasicPlaybackSampleApp/BasicPlaybackSampleApp/Players/BasicSimplePlayerViewController.m
> +#import <OoyalaSDK/OOEnums.h>
Done

2019-04-17 09:47 UTC, oSulyma commented on BasicPlaybackSampleApp/BasicPlaybackSampleApp/Players/BasicSimplePlayerViewController.m
>  #import <OoyalaSDK/OoyalaSDK.h>
Done

2019-05-15 09:54 UTC, maxkupetskii approved these changes

2019-05-16 16:01 UTC, cacel approved these changes
LGTM

2019-05-20 11:58 UTC, DmitriiMaslov approved these changes

2019-05-20 12:00 UTC, merged