[PLAYER-5615] ContentProtectionSampleApp updated
ooyala/ios-sample-apps pull request #397
Opened 2019-05-24 11:52 UTC by maxkupetskii

- uses `OptionsDataSource`
- uses `BasicEmbedTokenGenerator`

2019-05-24 15:55 UTC, cacel approved these changes

2019-05-30 13:17 UTC, oSulyma requested changes
I added six comments/remarks.

2019-05-30 13:17 UTC, oSulyma commented on ContentProtectionSampleApp/ContentProtectionSampleApp/Lists/ContentProtectionListViewController.m
> +  _options = OptionsDataSource.options;
Please use `self.` according to our code style.
Is it intended that all three properties are atomic? ([By default, an Objective-C property is atomic](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/EncapsulatingData/EncapsulatingData.html#//apple_ref/doc/uid/TP40011210-CH5-SW2))

2019-05-30 13:17 UTC, oSulyma commented on ContentProtectionSampleApp/ContentProtectionSampleApp/Players/DeviceManagementPlayerViewController.m
> +  }
Please, use iVars above

2019-05-30 13:17 UTC, oSulyma commented on ContentProtectionSampleApp/ContentProtectionSampleApp/Players/DeviceManagementPlayerViewController.m
> +   * The API Key and Secret should not be saved inside your applciation (even in git!).
Typo in word **applciation**

2019-05-30 13:17 UTC, oSulyma commented on ContentProtectionSampleApp/ContentProtectionSampleApp/Players/DeviceManagementPlayerViewController.m
> +    self.authorizeHost = tokenGenerator.authorizeHost;
Why most of properties above don't have `nonatomic` attribute? Taking in account that getter and setter for `atomic` are more expensive methods, I tends not to use it without reasoning.


.

2019-05-30 13:17 UTC, oSulyma commented on ContentProtectionSampleApp/ContentProtectionSampleApp/Players/FairplayPlayerViewController.m
>     * The API Key and Secret should not be saved inside your applciation (even in git!).
Typo in **applciation**

2019-05-30 13:17 UTC, oSulyma commented on ContentProtectionSampleApp/ContentProtectionSampleApp/Players/DeviceManagementPlayerViewController.m
>  @interface DeviceManagementPlayerViewController () <OOEmbedTokenGenerator>
Please add #pragma marks, at least for implementation `OOEmbedTokenGenerator ` protocol

2019-05-30 13:51 UTC, maxkupetskii commented on ContentProtectionSampleApp/ContentProtectionSampleApp/Lists/ContentProtectionListViewController.m
> +  _options = OptionsDataSource.options;
1. `viewDidLoad` can be treated as `init`
2. I did not change those properties and their characteristics.

2019-05-30 13:57 UTC, maxkupetskii commented on ContentProtectionSampleApp/ContentProtectionSampleApp/Players/DeviceManagementPlayerViewController.m
>  @interface DeviceManagementPlayerViewController () <OOEmbedTokenGenerator>
What for? It's purely optional thing

2019-05-30 14:02 UTC, oSulyma commented on ContentProtectionSampleApp/ContentProtectionSampleApp/Players/DeviceManagementPlayerViewController.m
>  @interface DeviceManagementPlayerViewController () <OOEmbedTokenGenerator>
More useful. Agree, optional.

2019-05-30 14:05 UTC, merged