[PLAYER-5605] Switch to next video causes the playback not start from begining
ooyala/ios-sample-apps pull request #398
Opened 2019-06-14 09:20 UTC by oSulyma

**Ticket goal:** Next asset should start from beginning or it's previous time
**How PR achieves the goal:** When VC hets notification `OOOoyalaPlayerStateChanged` player started playback from withInitialTime of appropriate selection options. But sometimes selection option can wrong defined (because of scrolling I assume), that why I added method for checking if embed code of selection option matches embed code of player's current item.

**Affected repo-s:** Sample-Apps only
**Unit tests:** Unit test not added, there is no Unit tests target

2019-06-14 09:22 UTC, oSulyma commented
@cacel  Please, pay attention to this PR, because you know about this SampleApp much more than other. 
Thank you

2019-06-14 10:01 UTC, maxkupetskii requested changes

2019-06-14 10:01 UTC, maxkupetskii commented on PlaybackLab/MultiplePlayersScrollingViewSampleApp/MultiplePlayersScrollingViewSampleApp/ViewControllers/MultiplePlayerViewController.swift
> +        indexPathForVisibleCell = collectionView.indexPath(for: cell)!
Please, do not force unwrap optionals

2019-06-14 10:01 UTC, maxkupetskii commented on PlaybackLab/MultiplePlayersScrollingViewSampleApp/MultiplePlayersScrollingViewSampleApp/ViewControllers/MultiplePlayerViewController.swift
> +
Please, remove extra line

2019-06-14 10:01 UTC, maxkupetskii commented on PlaybackLab/MultiplePlayersScrollingViewSampleApp/MultiplePlayersScrollingViewSampleApp/ViewControllers/MultiplePlayerViewController.swift
> +      //print("❌ ❌ ❌ playerSelection Option embedCode [\(selectionOption.embedCode)]. player.currentItem.embedCode: \(String(describing: sharedPlayer.player.currentItem.embedCode))")
Please, remove commented line

2019-06-14 10:52 UTC, oSulyma commented on PlaybackLab/MultiplePlayersScrollingViewSampleApp/MultiplePlayersScrollingViewSampleApp/ViewControllers/MultiplePlayerViewController.swift
> +        indexPathForVisibleCell = collectionView.indexPath(for: cell)!
It's not my code, but agree, it's dangerous approach. Fixed

2019-06-14 10:52 UTC, oSulyma commented on PlaybackLab/MultiplePlayersScrollingViewSampleApp/MultiplePlayersScrollingViewSampleApp/ViewControllers/MultiplePlayerViewController.swift
> +
Done

2019-06-14 10:52 UTC, oSulyma commented on PlaybackLab/MultiplePlayersScrollingViewSampleApp/MultiplePlayersScrollingViewSampleApp/ViewControllers/MultiplePlayerViewController.swift
> +      //print("❌ ❌ ❌ playerSelection Option embedCode [\(selectionOption.embedCode)]. player.currentItem.embedCode: \(String(describing: sharedPlayer.player.currentItem.embedCode))")
Done

2019-06-14 13:58 UTC, maxkupetskii approved these changes

2019-06-17 08:23 UTC, DmitriiMaslov approved these changes

2019-06-17 08:24 UTC, merged